# docker-compose.yaml
version: '3.4'

networks:
  dev:
    driver: bridge
    
services:

  rihal_cinema:
    image: docker.io/library/rihal_cinema
    depends_on:
      - app_db
      - minio
    container_name: rihal_cinema-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=SampleDbDriver;IntegratedSecurity=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDbDriver
    ports:
      - "5433:5432"
    restart: always
    # volumes:
    #   - app_data:/var/lib/postgresql/data
    networks:
      - dev
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
        MINIO_ROOT_USER: ROOTUSER
        MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
    - ./data:/data 
    networks:
    - dev
    
volumes:
  app_data:
